"""empty message

Revision ID: 841dfca8f0a0
Revises: 003f56a0b25a
Create Date: 2023-05-16 06:35:34.681454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '841dfca8f0a0'
down_revision = '003f56a0b25a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authors')
    # ### end Alembic commands ###
